language: python
python: 3.6
env: TRAVIS_NODE_VERSION=10

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install:
  - "pip install poetry"
  - "poetry install"
script: "lektor deploy"
deploy:
  provider: script
  script: "lektor deploy ghpages"
  on:
    branch: master
branches:
  only:
    - master